DROP TABLE IF EXISTS `population`;

CREATE TABLE IF NOT EXISTS `population` (
  `id` int NOT NULL AUTO_INCREMENT,
  `yyyy_mm` varchar(50) NOT NULL,
  `reg_se_cd` varchar(50) NOT NULL,
  `ctpv_nm` varchar(50) NOT NULL,
  `dong_nm` varchar(50) NOT NULL,
  `tong` varchar(50) NOT NULL,
  `ban` varchar(50) NOT NULL,
  `li_nm` varchar(50) NOT NULL,
  `stdg_cd` varchar(50) NOT NULL,
  `stdg_nm` varchar(50) NOT NULL,
  `sgg_nm` varchar(50) NOT NULL,
  `admm_cd` varchar(50) NOT NULL,
  `male_0_age_nmpr_cnt` int NOT NULL,
  `feml_0_age_nmpr_cnt` int NOT NULL,
  `male_10_age_nmpr_cnt` int NOT NULL,
  `feml_10_age_nmpr_cnt` int NOT NULL,
  `male_20_age_nmpr_cnt` int NOT NULL,
  `feml_20_age_nmpr_cnt` int NOT NULL,
  `male_30_age_nmpr_cnt` int NOT NULL,
  `feml_30_age_nmpr_cnt` int NOT NULL,
  `male_40_age_nmpr_cnt` int NOT NULL,
  `feml_40_age_nmpr_cnt` int NOT NULL,
  `male_50_age_nmpr_cnt` int NOT NULL,
  `feml_50_age_nmpr_cnt` int NOT NULL,
  `male_60_age_nmpr_cnt` int NOT NULL,
  `feml_60_age_nmpr_cnt` int NOT NULL,
  `male_70_age_nmpr_cnt` int NOT NULL,
  `feml_70_age_nmpr_cnt` int NOT NULL,
  `male_80_age_nmpr_cnt` int NOT NULL,
  `feml_80_age_nmpr_cnt` int NOT NULL,
  `male_90_age_nmpr_cnt` int NOT NULL,
  `feml_90_age_nmpr_cnt` int NOT NULL,
  `male_100_age_nmpr_cnt` int NOT NULL,
  `feml_100_age_nmpr_cnt` int NOT NULL,
  `male_nmpr_cnt` int NOT NULL,
  `feml_nmpr_cnt` int NOT NULL,
  `tot_nmpr_cnt` int NOT NULL,
  `stats_ym` varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
);
